name: Build kernel

on:
  push:
    paths:
      - "kernel/**"
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/build-kernel.yml"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4

      - name: Debug - CPU SYSINFO
        run: |
          echo "=== lscpu ==="
          lscpu
          echo "=== /proc/cpuinfo (core) ==="
          grep -m1 -A25 "^processor" /proc/cpuinfo

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            max-jobs = auto
            cores = 0

      - uses: cachix/cachix-action@v15
        with:
          name: ${{ secrets.CACHIX_CACHE_NAME }}
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Kernel Building
        run: nix build .#customKernel --keep-going -j auto --cores 0 -L

      - name: Kernel Artifact Upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build
          path: result/
          if-no-files-found: ignore